name: Groups
version: '${project.version}'
main: at.noah.groups.Groups
api-version: 1.18
authors: [ Leguan16 ]
description: A group plugin for sharing the same warps
commands:
  group:
    description: main command
  warp:
    description: warp yourself
